settings:
  title: 'Status Page'
  url: 'https://status2.ihrdc.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations
  ["kv-namespace id"] = e0be9ff0deab425b8d60d2e1f3918885
  kvNamespaceId:e0be9ff0deab425b8d60d2e1f3918885
  
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
- id: www-ihrdc-com
    name: www.ihrdc.com
    url: 'https://www.ihrdc.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
- id: player-ihrdc-com
    name: player.ihrdc.com
    url: 'https://player.ihrdc.com/a'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
- id: www-ipims-com
      name: www.ipims.com
      url: 'https://www.ipims.com'
      method: GET
      expectStatus: 200
      linkable: true # allows the title to be a link, default=true
- id: www-petroleumonline-com
      name: www.petroleumonline.com
      url: 'https://www.petroleumonline.com'
      method: GET
      expectStatus: 200
      linkable: true # allows the title to be a link, default=true
- id: demo-01-cm-ihrdc-net
      name: demo-01.cm.ihrdc.net
      url: 'https://demo-01.cm.ihrdc.net/'
      method: GET
      expectStatus: 200
      linkable: true # allows the title to be a link, default=true      
