name = "ihrdc-status-page"
workers_dev = true
type = "webpack"
account_id=""
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#route="status2.ihrdc.com/*"
