name = "cf-workers-status-page"
workers_dev = true
account_id = "9dd993fc59d4349163da673586e17dd8"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
kv-namespaces = [{binding="KV_STATUS_PAGE", id="e0be9ff0deab425b8d60d2e1f3918885", preview_id=""}]
zone_id="a176737ec682591d9b7c503e1ea5244d"
#route="xxx"
